### ISSUE TITLE
Unpacked 4K map is empty (only 141 bytes);

### ISSUE THREAD

**Issue by Ionwerks** [arma3/MipMapTool#1]
```
> mipmaptool unpack "altis_mca.paa"

Unpacking files:
Texture read "altis_mca.paa"
        Got mipmap size 4096x4096
        Got mipmap size 2048x2048
        Got mipmap size 1024x1024
        Got mipmap size 512x512
        Got mipmap size 256x256
        Got mipmap size 128x128
        Got mipmap size 64x64
        Got mipmap size 32x32
        Got mipmap size 16x16
        Got mipmap size 8x8
        Got mipmap size 4x4
        mipmaps=11
        isAlpha=1
        isTransparent=0
        avgColor=91626e6d
        maxColor=ffffffff

> dir /od altis*_mca.paa

01/09/2019  07:03        22,369,827 altis_mca.paa
01/09/2019  07:42               141 altis_mip4096_mca.paa
01/09/2019  07:42         4,194,445 altis_mip2048_mca.paa
01/09/2019  07:42         1,048,717 altis_mip1024_mca.paa
01/09/2019  07:42           262,285 altis_mip512_mca.paa
01/09/2019  07:42            65,677 altis_mip256_mca.paa
01/09/2019  07:42            16,525 altis_mip128_mca.paa
01/09/2019  07:42             4,237 altis_mip64_mca.paa
01/09/2019  07:42             1,165 altis_mip32_mca.paa
01/09/2019  07:42               397 altis_mip16_mca.paa
01/09/2019  07:42               205 altis_mip8_mca.paa
01/09/2019  07:42               157 altis_mip4_mca.paa
```

**Comment by dedmen** [comment]
Can you send me the texture you're having problems with? otherwise it'd be pretty hard to diagnose.

**Comment by Ionwerks** [comment]
Sure; https://www.filedropper.com/altismca

**Comment by dedmen** [comment]
Fault is in the paa. first mipmap is resolution 4096x4096.
But it's data size is 0.
![](https://s.sqf.ovh/HxD_2019-09-01_14-16-41.png)

**Comment by dedmen** [comment]
v4 release is pushed.

**Comment by Ionwerks** [comment]
Interesting, that would suggest PAA can't accommodate RGBA at 4K (size can't be contained in UInt24).

**Comment by dedmen** [comment]
I would've expected that mip to be compressed, but it wasn't. With compression enabled you probably could.

**Comment by Ionwerks** [comment]
Nature of the image (pre-generated noise) probably defies useful compression (possibly TexView decided that it wasn't worthwhile).

**Comment by dedmen** [comment]
My TexConvert.cfg has not `mca` postfix in it. I guess if postfix is not known, it's just written as uncompressed RGBA.

Actually the data size is 0xFFFFFF which would technically fit. But knowing Arma, they are probably using signed 24bit int....

Yuup, confirmed 24bit signed integer. GG.

It's only used for DXT compressed textures though.
Will investigate further, nice find!

**Comment by dedmen** [comment]
You are right, The compressed texture result is only used if compressedSize<uncompressedSize
