### ISSUE TITLE
Mip file naming.

### ISSUE THREAD

**Issue by Ionwerks** [arma3/MipMapTool#2]
Just wanted to suggest that a different naming scheme for the individual mip files would make it easier to automate processing using batch files. Presently the mip level is notated *within* the filename which means they cannot be readily matched by appending a prefix or suffix to the %~n1 variable macro (which returns only the file name, sans-path/extension),

Were they named (for instance) texture_co.mip4.paa one could write a batch file to (for instance) unpack and then repack leaving out the last 3 mip levels;

```
@echo off
if exist %~n1.mip*.paa del /y %~n1.mip*.paa
mipmaptool unpack %1
del %1
mipmaptool output %1 %~n1.mip2048.paa %~n1.mip1024.paa %~n1.mip512.paa  %~n1.mip256.paa  %~n1.mip128.paa  %~n1.mip64.paa %~n1.mip32.paa
pause
```

**Comment by dedmen** [comment]
the name matching is just done with a simple regex, I could let you provide that regex.
But that wouldn't work for unpack.
Maybe a parameter with different styles. Just like "-namestyle 2" ?

**Comment by Ionwerks** [comment]
Sounds like a plan, and would save upsetting any scripts people might already be using.

**Comment by dedmen** [comment]
This should be what you wanted right? Can you think of any other styles that people might want?
I guess I can always just add it once someone asks.

**Comment by Ionwerks** [comment]
Yep, nice one, thanks. No I can't think of any other requirement for naming (but you've indexed/numbered -namestyle so it'd be easy to add if somebody does come up with one).
